// coding: utf-8
//
// ONLY READ THIS IF YOU HAVE ALREADY SOLVED THIS PROBLEM!
// File created for http://projecteuler.net/
//
// Created by: Alex Dias Teixeira
// Name:       002_fibonacci.py
// Date:       08 Sept 2013
//
// Problem:    [2] - Even Fibonnaci numbers
//   Each new term in the Fibonacci sequence is generated by adding the
//   previous two terms. By starting with 1 and 2, the first 10 terms will
//   be:
//
//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
//   By considering the terms in the Fibonacci sequence whose values do not
//   exceed four million, find the sum of the even-valued terms.
//

// This function maybe over the top for this problem.

import UIKit

var total = 0

for i in Range(start: 0, end: 1000) {
    if (i % 3 == 0) || (i % 5 == 0) {
        total = total + i
    }
}
